{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "c911c8a3",
   "metadata": {},
   "source": [
    "## Обработка исключений"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "daa95f3a",
   "metadata": {},
   "source": [
    "Программа выполняется последовательно, сверху вниз. Если вдруг посередине программы встречается ошибка (исключение), то она останавливает свою работу, и строки кода, следующие после ошибки, не выпоняются."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "30e3a5d7",
   "metadata": {},
   "source": [
    "Ошибки, которые возникают в процессе программы, называются исключениями в процессе выполнения. Есть еще исключения в процессе компиляции (как правило, синтаксические ошибки). Если встречается ошибка в процессе компиляции - программа даже не будет запущена."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d127c35e",
   "metadata": {},
   "source": [
    "Поэтому исключения делятся на дву группы:<br>\n",
    "    1) Исключения в момент исполнения<br>\n",
    "    2) Исключения при компиляции (до исполнения кода)<br>"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2e723069",
   "metadata": {},
   "source": [
    "Когда выполняется обработка исключений, ведется работа с исключениями в момент исполнения кода."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8ad058bc",
   "metadata": {},
   "outputs": [],
   "source": [
    "a = 0"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2f186f64",
   "metadata": {},
   "source": [
    "Для обработки исключений существует специальный оператор try. В него помещается критический блок кода, в котором возможно возникновение ошибки. Если он выполнится, дополнительно ничего не произойдет. А если нет, то запустится код, который находится во втором блоке except:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c3b97c13",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Ошибка! Деление на ноль невозможно\n",
      "Штатное завершение\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    1/a\n",
    "except ZeroDivisionError:\n",
    "    print('Ошибка! Деление на ноль невозможно')\n",
    "    \n",
    "print('Штатное завершение')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d8551b00",
   "metadata": {},
   "source": [
    "После ключевой фразы except прописывается имя ошибки, которая обрабатывается. При этом программа аварийно не завершается - она продолжает свою работу."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1bd20218",
   "metadata": {},
   "source": [
    "Обработка исключений предполагает, что программа аварийно не завершается и продолжает свою работу."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fd3dc8c5",
   "metadata": {},
   "source": [
    "Если требуется обработать несколько видов ошибок - допускается запись нескольких блоков Except друг за другом:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "88fdffcd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Ошибка! Деление на ноль невозможно\n",
      "Штатное завершение\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    1/a\n",
    "except ZeroDivisionError:\n",
    "    print('Ошибка! Деление на ноль невозможно')\n",
    "except Exception:\n",
    "    print('Общая ошибка')\n",
    "    \n",
    "print('Штатное завершение')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "73b7bf6c",
   "metadata": {},
   "source": [
    "И в зависимости от того, какое исключение возникнет, тот блок except и будет работать. Чтобы отловить в одном блоке except сразу несколько исключений, их можно записывать в круглых скобках:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "08b7d70b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Ошибка! Деление на ноль невозможно\n",
      "Штатное завершение\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    '1'/a\n",
    "except (ZeroDivisionError, TypeError, ValueError):\n",
    "    print('Ошибка! Деление на ноль невозможно')\n",
    "except Exception:\n",
    "    print('Общая ошибка')\n",
    "    \n",
    "print('Штатное завершение')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0ca28d4a",
   "metadata": {},
   "source": [
    "Существует определенная иерархия классов исключений, во главе которой стоит базовый класс Base Exception. А большая часть классов наследуется от класса Exception. Если в блоке except указать какой либо базовый класс, то автоматически будут обрабатыватся и все исключения, что от него наследуются. Так как движение по блокам except осуществляется сверху вниз, то сначала нужно указывать блоки со специализированными исключениями, а затем - с общими, базовыми. Также блок except можно прописывать без каких либо классов - и тогда в нем будут отлавливаться аюсолютно все исключения."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
